package com.rainya.mapper;

import com.rainya.po.PersistentLogins;
import com.rainya.po.PersistentLoginsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersistentLoginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int countByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int deleteByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    List<PersistentLogins> selectByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    PersistentLogins selectByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersistentLogins record);
}