package com.rainya.mapper;

import com.rainya.po.RyBanner;
import com.rainya.po.RyBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RyBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int countByExample(RyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int deleteByExample(RyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int insert(RyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int insertSelective(RyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    List<RyBanner> selectByExample(RyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    RyBanner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RyBanner record, @Param("example") RyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RyBanner record, @Param("example") RyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RyBanner record);
}