package com.rainya.mapper;

import com.rainya.po.RyProgram;
import com.rainya.po.RyProgramExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RyProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int countByExample(RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int deleteByExample(RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int insert(RyProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int insertSelective(RyProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    List<RyProgram> selectByExampleWithBLOBs(RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    List<RyProgram> selectByExample(RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    RyProgram selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RyProgram record, @Param("example") RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RyProgram record, @Param("example") RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RyProgram record, @Param("example") RyProgramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RyProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RyProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_program
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RyProgram record);
}