package com.rainya.mapper;

import com.rainya.po.SecSysRolesAuthorities;
import com.rainya.po.SecSysRolesAuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecSysRolesAuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int countByExample(SecSysRolesAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int deleteByExample(SecSysRolesAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int insert(SecSysRolesAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int insertSelective(SecSysRolesAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    List<SecSysRolesAuthorities> selectByExample(SecSysRolesAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    SecSysRolesAuthorities selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecSysRolesAuthorities record, @Param("example") SecSysRolesAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecSysRolesAuthorities record, @Param("example") SecSysRolesAuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecSysRolesAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles_authorities
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecSysRolesAuthorities record);
}