package com.rainya.mapper;

import com.rainya.po.SecSysUsers;
import com.rainya.po.SecSysUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecSysUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int countByExample(SecSysUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int deleteByExample(SecSysUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int insert(SecSysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int insertSelective(SecSysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    List<SecSysUsers> selectByExample(SecSysUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    SecSysUsers selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecSysUsers record, @Param("example") SecSysUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecSysUsers record, @Param("example") SecSysUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecSysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecSysUsers record);
}