package com.rainya.mapper;

import com.rainya.po.SecSysUsersRoles;
import com.rainya.po.SecSysUsersRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecSysUsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int countByExample(SecSysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SecSysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int insert(SecSysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int insertSelective(SecSysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    List<SecSysUsersRoles> selectByExample(SecSysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    SecSysUsersRoles selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecSysUsersRoles record, @Param("example") SecSysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecSysUsersRoles record, @Param("example") SecSysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecSysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecSysUsersRoles record);
}