package com.rainya.mapper;

import com.rainya.po.SecSysRoles;
import com.rainya.po.SecSysRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecSysRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int countByExample(SecSysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SecSysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int insert(SecSysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int insertSelective(SecSysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    List<SecSysRoles> selectByExample(SecSysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    SecSysRoles selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecSysRoles record, @Param("example") SecSysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecSysRoles record, @Param("example") SecSysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecSysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_sys_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecSysRoles record);
}