package com.rainya.po;

import java.util.Date;

public class PersistentLogins {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.SERIES
     *
     * @mbggenerated
     */
    private String series;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.LAST_USED
     *
     * @mbggenerated
     */
    private Date lastUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.SERIES
     *
     * @return the value of persistent_logins.SERIES
     *
     * @mbggenerated
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.SERIES
     *
     * @param series the value for persistent_logins.SERIES
     *
     * @mbggenerated
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.USERNAME
     *
     * @return the value of persistent_logins.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.USERNAME
     *
     * @param username the value for persistent_logins.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.TOKEN
     *
     * @return the value of persistent_logins.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.TOKEN
     *
     * @param token the value for persistent_logins.TOKEN
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.LAST_USED
     *
     * @return the value of persistent_logins.LAST_USED
     *
     * @mbggenerated
     */
    public Date getLastUsed() {
        return lastUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.LAST_USED
     *
     * @param lastUsed the value for persistent_logins.LAST_USED
     *
     * @mbggenerated
     */
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }
}