package com.rainya.po;

import java.util.Date;

public class RyProgram {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.NAME_CN
     *
     * @mbggenerated
     */
    private String nameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.NAME_EN
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.PARENT_ID
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.ICON_URL
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.SUB_TITLE
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.IMG_PREVIEW_URL
     *
     * @mbggenerated
     */
    private String imgPreviewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.SHOW_ORDER
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.MODIFY_DATE
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_program.CONTENT
     *
     * @mbggenerated
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.ID
     *
     * @return the value of ry_program.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.ID
     *
     * @param id the value for ry_program.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.NAME_CN
     *
     * @return the value of ry_program.NAME_CN
     *
     * @mbggenerated
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.NAME_CN
     *
     * @param nameCn the value for ry_program.NAME_CN
     *
     * @mbggenerated
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn == null ? null : nameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.NAME_EN
     *
     * @return the value of ry_program.NAME_EN
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.NAME_EN
     *
     * @param nameEn the value for ry_program.NAME_EN
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.DESCRIPTION
     *
     * @return the value of ry_program.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.DESCRIPTION
     *
     * @param description the value for ry_program.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.URL
     *
     * @return the value of ry_program.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.URL
     *
     * @param url the value for ry_program.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.STATUS
     *
     * @return the value of ry_program.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.STATUS
     *
     * @param status the value for ry_program.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.PARENT_ID
     *
     * @return the value of ry_program.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.PARENT_ID
     *
     * @param parentId the value for ry_program.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.ICON_URL
     *
     * @return the value of ry_program.ICON_URL
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.ICON_URL
     *
     * @param iconUrl the value for ry_program.ICON_URL
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.TITLE
     *
     * @return the value of ry_program.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.TITLE
     *
     * @param title the value for ry_program.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.SUB_TITLE
     *
     * @return the value of ry_program.SUB_TITLE
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.SUB_TITLE
     *
     * @param subTitle the value for ry_program.SUB_TITLE
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.IMG_PREVIEW_URL
     *
     * @return the value of ry_program.IMG_PREVIEW_URL
     *
     * @mbggenerated
     */
    public String getImgPreviewUrl() {
        return imgPreviewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.IMG_PREVIEW_URL
     *
     * @param imgPreviewUrl the value for ry_program.IMG_PREVIEW_URL
     *
     * @mbggenerated
     */
    public void setImgPreviewUrl(String imgPreviewUrl) {
        this.imgPreviewUrl = imgPreviewUrl == null ? null : imgPreviewUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.SHOW_ORDER
     *
     * @return the value of ry_program.SHOW_ORDER
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.SHOW_ORDER
     *
     * @param showOrder the value for ry_program.SHOW_ORDER
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.CREATE_DATE
     *
     * @return the value of ry_program.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.CREATE_DATE
     *
     * @param createDate the value for ry_program.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.MODIFY_DATE
     *
     * @return the value of ry_program.MODIFY_DATE
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.MODIFY_DATE
     *
     * @param modifyDate the value for ry_program.MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_program.CONTENT
     *
     * @return the value of ry_program.CONTENT
     *
     * @mbggenerated
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_program.CONTENT
     *
     * @param content the value for ry_program.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}