package com.rainya.po;

public class SecSysResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.RESOURCE_NAME
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.RESOURCE_DESC
     *
     * @mbggenerated
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.RESOURCE_PATH
     *
     * @mbggenerated
     */
    private String resourcePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.PRIORITY
     *
     * @mbggenerated
     */
    private String priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.ENABLE
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.ISSEC_SYS
     *
     * @mbggenerated
     */
    private Integer issecSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_resources.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.RESOURCE_ID
     *
     * @return the value of sec_sys_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.RESOURCE_ID
     *
     * @param resourceId the value for sec_sys_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.RESOURCE_TYPE
     *
     * @return the value of sec_sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.RESOURCE_TYPE
     *
     * @param resourceType the value for sec_sys_resources.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.RESOURCE_NAME
     *
     * @return the value of sec_sys_resources.RESOURCE_NAME
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.RESOURCE_NAME
     *
     * @param resourceName the value for sec_sys_resources.RESOURCE_NAME
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.RESOURCE_DESC
     *
     * @return the value of sec_sys_resources.RESOURCE_DESC
     *
     * @mbggenerated
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.RESOURCE_DESC
     *
     * @param resourceDesc the value for sec_sys_resources.RESOURCE_DESC
     *
     * @mbggenerated
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.RESOURCE_PATH
     *
     * @return the value of sec_sys_resources.RESOURCE_PATH
     *
     * @mbggenerated
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.RESOURCE_PATH
     *
     * @param resourcePath the value for sec_sys_resources.RESOURCE_PATH
     *
     * @mbggenerated
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath == null ? null : resourcePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.PRIORITY
     *
     * @return the value of sec_sys_resources.PRIORITY
     *
     * @mbggenerated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.PRIORITY
     *
     * @param priority the value for sec_sys_resources.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.ENABLE
     *
     * @return the value of sec_sys_resources.ENABLE
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.ENABLE
     *
     * @param enable the value for sec_sys_resources.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.ISSEC_SYS
     *
     * @return the value of sec_sys_resources.ISSEC_SYS
     *
     * @mbggenerated
     */
    public Integer getIssecSys() {
        return issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.ISSEC_SYS
     *
     * @param issecSys the value for sec_sys_resources.ISSEC_SYS
     *
     * @mbggenerated
     */
    public void setIssecSys(Integer issecSys) {
        this.issecSys = issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_resources.MODULE_ID
     *
     * @return the value of sec_sys_resources.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_resources.MODULE_ID
     *
     * @param moduleId the value for sec_sys_resources.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}