package com.rainya.po;

import java.util.Date;

public class SecSysUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.DT_CREATE
     *
     * @mbggenerated
     */
    private Date dtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.LAST_LOGIN
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.DEADLINE
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.LOGIN_IP
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.V_QZJGID
     *
     * @mbggenerated
     */
    private String vQzjgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.V_QZJGMC
     *
     * @mbggenerated
     */
    private String vQzjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.DEP_ID
     *
     * @mbggenerated
     */
    private String depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.DEP_NAME
     *
     * @mbggenerated
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.ENABLED
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.ACCOUNT_NON_EXPIRED
     *
     * @mbggenerated
     */
    private Integer accountNonExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.ACCOUNT_NON_LOCKED
     *
     * @mbggenerated
     */
    private Integer accountNonLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_users.CREDENTIALS_NON_EXPIRED
     *
     * @mbggenerated
     */
    private Integer credentialsNonExpired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.USER_ID
     *
     * @return the value of sec_sys_users.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.USER_ID
     *
     * @param userId the value for sec_sys_users.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.USERNAME
     *
     * @return the value of sec_sys_users.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.USERNAME
     *
     * @param username the value for sec_sys_users.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.NAME
     *
     * @return the value of sec_sys_users.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.NAME
     *
     * @param name the value for sec_sys_users.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.PASSWORD
     *
     * @return the value of sec_sys_users.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.PASSWORD
     *
     * @param password the value for sec_sys_users.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.DT_CREATE
     *
     * @return the value of sec_sys_users.DT_CREATE
     *
     * @mbggenerated
     */
    public Date getDtCreate() {
        return dtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.DT_CREATE
     *
     * @param dtCreate the value for sec_sys_users.DT_CREATE
     *
     * @mbggenerated
     */
    public void setDtCreate(Date dtCreate) {
        this.dtCreate = dtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.LAST_LOGIN
     *
     * @return the value of sec_sys_users.LAST_LOGIN
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.LAST_LOGIN
     *
     * @param lastLogin the value for sec_sys_users.LAST_LOGIN
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.DEADLINE
     *
     * @return the value of sec_sys_users.DEADLINE
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.DEADLINE
     *
     * @param deadline the value for sec_sys_users.DEADLINE
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.LOGIN_IP
     *
     * @return the value of sec_sys_users.LOGIN_IP
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.LOGIN_IP
     *
     * @param loginIp the value for sec_sys_users.LOGIN_IP
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.V_QZJGID
     *
     * @return the value of sec_sys_users.V_QZJGID
     *
     * @mbggenerated
     */
    public String getvQzjgid() {
        return vQzjgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.V_QZJGID
     *
     * @param vQzjgid the value for sec_sys_users.V_QZJGID
     *
     * @mbggenerated
     */
    public void setvQzjgid(String vQzjgid) {
        this.vQzjgid = vQzjgid == null ? null : vQzjgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.V_QZJGMC
     *
     * @return the value of sec_sys_users.V_QZJGMC
     *
     * @mbggenerated
     */
    public String getvQzjgmc() {
        return vQzjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.V_QZJGMC
     *
     * @param vQzjgmc the value for sec_sys_users.V_QZJGMC
     *
     * @mbggenerated
     */
    public void setvQzjgmc(String vQzjgmc) {
        this.vQzjgmc = vQzjgmc == null ? null : vQzjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.DEP_ID
     *
     * @return the value of sec_sys_users.DEP_ID
     *
     * @mbggenerated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.DEP_ID
     *
     * @param depId the value for sec_sys_users.DEP_ID
     *
     * @mbggenerated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.DEP_NAME
     *
     * @return the value of sec_sys_users.DEP_NAME
     *
     * @mbggenerated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.DEP_NAME
     *
     * @param depName the value for sec_sys_users.DEP_NAME
     *
     * @mbggenerated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.ENABLED
     *
     * @return the value of sec_sys_users.ENABLED
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.ENABLED
     *
     * @param enabled the value for sec_sys_users.ENABLED
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.ACCOUNT_NON_EXPIRED
     *
     * @return the value of sec_sys_users.ACCOUNT_NON_EXPIRED
     *
     * @mbggenerated
     */
    public Integer getAccountNonExpired() {
        return accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.ACCOUNT_NON_EXPIRED
     *
     * @param accountNonExpired the value for sec_sys_users.ACCOUNT_NON_EXPIRED
     *
     * @mbggenerated
     */
    public void setAccountNonExpired(Integer accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.ACCOUNT_NON_LOCKED
     *
     * @return the value of sec_sys_users.ACCOUNT_NON_LOCKED
     *
     * @mbggenerated
     */
    public Integer getAccountNonLocked() {
        return accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.ACCOUNT_NON_LOCKED
     *
     * @param accountNonLocked the value for sec_sys_users.ACCOUNT_NON_LOCKED
     *
     * @mbggenerated
     */
    public void setAccountNonLocked(Integer accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_users.CREDENTIALS_NON_EXPIRED
     *
     * @return the value of sec_sys_users.CREDENTIALS_NON_EXPIRED
     *
     * @mbggenerated
     */
    public Integer getCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_users.CREDENTIALS_NON_EXPIRED
     *
     * @param credentialsNonExpired the value for sec_sys_users.CREDENTIALS_NON_EXPIRED
     *
     * @mbggenerated
     */
    public void setCredentialsNonExpired(Integer credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }
}