package com.rainya.po;

public class SecSysAuthorities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated
     */
    private String authorityMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated
     */
    private String authorityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.MESSAGE
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.ENABLE
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.ISSEC_SYS
     *
     * @mbggenerated
     */
    private Integer issecSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.AUTHORITY_ID
     *
     * @return the value of sec_sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.AUTHORITY_ID
     *
     * @param authorityId the value for sec_sys_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.AUTHORITY_MARK
     *
     * @return the value of sec_sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated
     */
    public String getAuthorityMark() {
        return authorityMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.AUTHORITY_MARK
     *
     * @param authorityMark the value for sec_sys_authorities.AUTHORITY_MARK
     *
     * @mbggenerated
     */
    public void setAuthorityMark(String authorityMark) {
        this.authorityMark = authorityMark == null ? null : authorityMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.AUTHORITY_NAME
     *
     * @return the value of sec_sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.AUTHORITY_NAME
     *
     * @param authorityName the value for sec_sys_authorities.AUTHORITY_NAME
     *
     * @mbggenerated
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.AUTHORITY_DESC
     *
     * @return the value of sec_sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated
     */
    public String getAuthorityDesc() {
        return authorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.AUTHORITY_DESC
     *
     * @param authorityDesc the value for sec_sys_authorities.AUTHORITY_DESC
     *
     * @mbggenerated
     */
    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc == null ? null : authorityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.MESSAGE
     *
     * @return the value of sec_sys_authorities.MESSAGE
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.MESSAGE
     *
     * @param message the value for sec_sys_authorities.MESSAGE
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.ENABLE
     *
     * @return the value of sec_sys_authorities.ENABLE
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.ENABLE
     *
     * @param enable the value for sec_sys_authorities.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.ISSEC_SYS
     *
     * @return the value of sec_sys_authorities.ISSEC_SYS
     *
     * @mbggenerated
     */
    public Integer getIssecSys() {
        return issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.ISSEC_SYS
     *
     * @param issecSys the value for sec_sys_authorities.ISSEC_SYS
     *
     * @mbggenerated
     */
    public void setIssecSys(Integer issecSys) {
        this.issecSys = issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities.MODULE_ID
     *
     * @return the value of sec_sys_authorities.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities.MODULE_ID
     *
     * @param moduleId the value for sec_sys_authorities.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}