package com.rainya.po;

public class SecSysRolesAuthorities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_authorities.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_authorities.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_authorities.ID
     *
     * @return the value of sec_sys_roles_authorities.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_authorities.ID
     *
     * @param id the value for sec_sys_roles_authorities.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_authorities.AUTHORITY_ID
     *
     * @return the value of sec_sys_roles_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_authorities.AUTHORITY_ID
     *
     * @param authorityId the value for sec_sys_roles_authorities.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_authorities.ROLE_ID
     *
     * @return the value of sec_sys_roles_authorities.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_authorities.ROLE_ID
     *
     * @param roleId the value for sec_sys_roles_authorities.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}