package com.rainya.po;

public class SecSysRolesMoudles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_moudles.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_moudles.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles_moudles.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_moudles.ID
     *
     * @return the value of sec_sys_roles_moudles.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_moudles.ID
     *
     * @param id the value for sec_sys_roles_moudles.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_moudles.MODULE_ID
     *
     * @return the value of sec_sys_roles_moudles.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_moudles.MODULE_ID
     *
     * @param moduleId the value for sec_sys_roles_moudles.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles_moudles.ROLE_ID
     *
     * @return the value of sec_sys_roles_moudles.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles_moudles.ROLE_ID
     *
     * @param roleId the value for sec_sys_roles_moudles.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}