package com.rainya.po;

public class SecSysAuthoritiesResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities_resources.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_authorities_resources.AUTHORITY_ID
     *
     * @mbggenerated
     */
    private String authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities_resources.ID
     *
     * @return the value of sec_sys_authorities_resources.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities_resources.ID
     *
     * @param id the value for sec_sys_authorities_resources.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities_resources.RESOURCE_ID
     *
     * @return the value of sec_sys_authorities_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities_resources.RESOURCE_ID
     *
     * @param resourceId the value for sec_sys_authorities_resources.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_authorities_resources.AUTHORITY_ID
     *
     * @return the value of sec_sys_authorities_resources.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_authorities_resources.AUTHORITY_ID
     *
     * @param authorityId the value for sec_sys_authorities_resources.AUTHORITY_ID
     *
     * @mbggenerated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }
}