package com.rainya.po;

public class SecSysModules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.MODULE_NAME
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.MODULE_DESC
     *
     * @mbggenerated
     */
    private String moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.MODULE_TYPE
     *
     * @mbggenerated
     */
    private String moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.PARENT
     *
     * @mbggenerated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.MODULE_URL
     *
     * @mbggenerated
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.I_LEVEL
     *
     * @mbggenerated
     */
    private Integer iLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.LEAF
     *
     * @mbggenerated
     */
    private Integer leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.APPLICATION
     *
     * @mbggenerated
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.CONTROLLER
     *
     * @mbggenerated
     */
    private String controller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.ENABLE
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_modules.PRIORITY
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.MODULE_ID
     *
     * @return the value of sec_sys_modules.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.MODULE_ID
     *
     * @param moduleId the value for sec_sys_modules.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.MODULE_NAME
     *
     * @return the value of sec_sys_modules.MODULE_NAME
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.MODULE_NAME
     *
     * @param moduleName the value for sec_sys_modules.MODULE_NAME
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.MODULE_DESC
     *
     * @return the value of sec_sys_modules.MODULE_DESC
     *
     * @mbggenerated
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.MODULE_DESC
     *
     * @param moduleDesc the value for sec_sys_modules.MODULE_DESC
     *
     * @mbggenerated
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.MODULE_TYPE
     *
     * @return the value of sec_sys_modules.MODULE_TYPE
     *
     * @mbggenerated
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.MODULE_TYPE
     *
     * @param moduleType the value for sec_sys_modules.MODULE_TYPE
     *
     * @mbggenerated
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType == null ? null : moduleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.PARENT
     *
     * @return the value of sec_sys_modules.PARENT
     *
     * @mbggenerated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.PARENT
     *
     * @param parent the value for sec_sys_modules.PARENT
     *
     * @mbggenerated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.MODULE_URL
     *
     * @return the value of sec_sys_modules.MODULE_URL
     *
     * @mbggenerated
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.MODULE_URL
     *
     * @param moduleUrl the value for sec_sys_modules.MODULE_URL
     *
     * @mbggenerated
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.I_LEVEL
     *
     * @return the value of sec_sys_modules.I_LEVEL
     *
     * @mbggenerated
     */
    public Integer getiLevel() {
        return iLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.I_LEVEL
     *
     * @param iLevel the value for sec_sys_modules.I_LEVEL
     *
     * @mbggenerated
     */
    public void setiLevel(Integer iLevel) {
        this.iLevel = iLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.LEAF
     *
     * @return the value of sec_sys_modules.LEAF
     *
     * @mbggenerated
     */
    public Integer getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.LEAF
     *
     * @param leaf the value for sec_sys_modules.LEAF
     *
     * @mbggenerated
     */
    public void setLeaf(Integer leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.APPLICATION
     *
     * @return the value of sec_sys_modules.APPLICATION
     *
     * @mbggenerated
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.APPLICATION
     *
     * @param application the value for sec_sys_modules.APPLICATION
     *
     * @mbggenerated
     */
    public void setApplication(String application) {
        this.application = application == null ? null : application.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.CONTROLLER
     *
     * @return the value of sec_sys_modules.CONTROLLER
     *
     * @mbggenerated
     */
    public String getController() {
        return controller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.CONTROLLER
     *
     * @param controller the value for sec_sys_modules.CONTROLLER
     *
     * @mbggenerated
     */
    public void setController(String controller) {
        this.controller = controller == null ? null : controller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.ENABLE
     *
     * @return the value of sec_sys_modules.ENABLE
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.ENABLE
     *
     * @param enable the value for sec_sys_modules.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_modules.PRIORITY
     *
     * @return the value of sec_sys_modules.PRIORITY
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_modules.PRIORITY
     *
     * @param priority the value for sec_sys_modules.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}