package com.rainya.po;

public class SecSysRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.ROLE_DESC
     *
     * @mbggenerated
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.ENABLE
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.ISSEC_SYS
     *
     * @mbggenerated
     */
    private Integer issecSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_sys_roles.MODULE_ID
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.ROLE_ID
     *
     * @return the value of sec_sys_roles.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.ROLE_ID
     *
     * @param roleId the value for sec_sys_roles.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.ROLE_NAME
     *
     * @return the value of sec_sys_roles.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.ROLE_NAME
     *
     * @param roleName the value for sec_sys_roles.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.ROLE_DESC
     *
     * @return the value of sec_sys_roles.ROLE_DESC
     *
     * @mbggenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.ROLE_DESC
     *
     * @param roleDesc the value for sec_sys_roles.ROLE_DESC
     *
     * @mbggenerated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.ENABLE
     *
     * @return the value of sec_sys_roles.ENABLE
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.ENABLE
     *
     * @param enable the value for sec_sys_roles.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.ISSEC_SYS
     *
     * @return the value of sec_sys_roles.ISSEC_SYS
     *
     * @mbggenerated
     */
    public Integer getIssecSys() {
        return issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.ISSEC_SYS
     *
     * @param issecSys the value for sec_sys_roles.ISSEC_SYS
     *
     * @mbggenerated
     */
    public void setIssecSys(Integer issecSys) {
        this.issecSys = issecSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_sys_roles.MODULE_ID
     *
     * @return the value of sec_sys_roles.MODULE_ID
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_sys_roles.MODULE_ID
     *
     * @param moduleId the value for sec_sys_roles.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}